## Presentations

### Invited Talks

1. **Roque, N.A.** (2025, May 20th). Detection of AI-Generated Information Across the Lifespan. In-person presentation for the IAFCI PA State Annual Conference in State College, PA.
1. **Roque, N.A.** (2025, March). Detection of AI-Generated Images Across the Lifespan. In-person presentation for the Mental Health Technology Center (MHTech) Seminar Series at the University of California San Diego.
1. **Roque, N.A.** (2024, May 10th). Breathe Well, Age Well. Virtual presentation as part of Stony Brook’s Cognitive Aging Colloquium.
1. **Roque, N.A.** (2024, January 22nd). Beyond Numbers: Unlocking Health Insights in Underserved Communities through mHealth Data Collection. In-person presentation and Q&A panel as part of UT Austin’s CAPS Panel on Ecological Momentary Assessments in Underrepresented Populations.
1. **Roque, N.A.** (2022, October 20th). Cognitive Assessment in the Cloud: Approaches & Lessons Learned. Virtual presentation as part of Amazon Web Services (AWS) Education Research Seminar Series.
1. **Roque, N.A.** (2022, October 6th). Cognitive Assessment in the Cloud: Approaches & Lessons Learned. In-person presentation at Union College. Schenectady, New York.
1. **Roque N.A.** (2020, August 20th). Leveraging Air Quality Sensors to Detect Smoking Behaviors. Virtual presentation at Pennsylvania State University x Monash University: Intersection of Health and the Environment.

### Organized Symposia

1. Harrington, K., **Roque, N.**, & Mogle, J. (2020, November). Approaches for Modeling of Intensive Longitudinal Data to Understand Cognitive Aging. Innovation in Aging, 4(Suppl 1), 565. Gerontological Society of America, 2020 Annual Meeting. – Symposium Co-Chair.
1. Sliwinski, M.J. and **Roque, N.A.** (2020, April). Increasing the Precision of Measuring Cognitive Function in Older Adults using Mobile Technologies. Cognitive Aging Conference, 2020 Annual Meeting. – Symposium Co-Organizer; accepted; conference cancelled due to COVID-19.
1. Roque, NA., Hyun, J., Scott, S. (2019, November). Using Mobile Technology to Elucidate Psychosocial and Cognitive Function in Older Adults. Innovation in Aging, 3(Supplement_1), S809-S810. Gerontological Society of America, 2019 Annual Meeting. – Symposium Chair.

### Conference Oral Presentations

1. Hyun, J., **Roque, N.**, Lovasi, G., Hosgood, D., Katz, M., Lipton, R., & Hall, C. (2025). Beyond Neighborhood Boundaries: GPS-Based Activity Space, Built Environment, and Cognitive Health. Innovation in Aging, 9(Supplement_2), igaf122.949. https://doi.org/10.1093/geroni/igaf122.949
1. De La Garza, A. G., Derby, C., Wang, C., Mogle, J., Lipton, R., **Roque, N.**, Katz, M., & Rabin, L. (2025). Perception to Performance: Linking Cognitive Lapses & Smartphone Cognitive Assessments in the Einstein Aging Study. Innovation in Aging, 9(Supplement_2), igaf122.1890. https://doi.org/10.1093/geroni/igaf122.1890
1. Shaleha, R., Almeida, D., & **Roque, N.** (2025). Daily Stress, Cortisol Dysregulation, and Screen Time in Midlife and Older Adults: Findings from the MIDUS Study. Innovation in Aging, 9(Supplement_2), igaf122.3065. https://doi.org/10.1093/geroni/igaf122.3065
1. Hoogendoorn, C., De La Garza, A. G., **Roque, N.**, Wang, C., Lipton, R., & Gonzalez, J. (2025). Wearable Continuous Glucose Monitoring and Cognitive Performance in Older Adults With Type 2 Diabetes. Innovation in Aging, 9(Supplement_2), igaf122.1889. https://doi.org/10.1093/geroni/igaf122.1889
1. Sergeyev, N., Bodek, H., Moffitt, C., Andrews, H. J., Cameron, J. D., Lavin, R., **Roque, N. A.**, Ezzati, A., Lipton, R. B., & Rabin, L. A. (2025, July 27). Impact of Sociodemographic and Linguistic Factors on TICS-m Screening: Findings from the Remote-CARE Study. Alzheimer’s Association International Conference. https://alz.confex.com/alz/2025/meetingapp.cgi/Paper/106205
1. Go Cheng, K. J., & **Roque, N. A.** (2025, July 27). Hitting the Brakes: Driving Cessation, Cognitive Health, and the Mediating Role of Social Relationships Among Older Adults in the U.S. Alzheimer’s Association International Conference. https://alz.confex.com/alz/2025/meetingapp.cgi/Paper/099940
1. Garcia De La Garza, A., Derby, C. A., Wang, C., **Roque, N. A.**, Katz, M. J., Lipton, R. B., & Rabin, L. A. (2025b, July 27). How Daily Experiences of Stress and Emotions Contextualize Subjective Cognitive Concerns: Findings from Daily Digital Diary Assessments in the Einstein Aging Study (EAS). Alzheimer’s Association International Conference. https://alz.confex.com/alz/2025/meetingapp.cgi/Paper/107552
1. Garcia De La Garza, A., Derby, C. A., Wang, C., **Roque, N.**, Katz, M. J., Lipton, R. B., & Rabin, L. A. (2025c, July 26). Elucidating the Association Between Pain and Self-Perceived Cognitive Functioning Using Daily Digital Diary Assessments: Results from the Einstein Aging Study (EAS). Alzheimer’s Association International Conference. https://alz.confex.com/alz/2025/meetingapp.cgi/Paper/110543
1. Garcia De La Garza, A., Derby, C. A., Wang, C., **Roque, N. A.**, Katz, M. J., Lipton, R. B., & Rabin, L. A. (2025a, July 26). Longitudinal Increases in Subjective Cognitive Concerns are associated with Changes in Global Cognitive Performance: Findings from Daily Digital Diary Assessments in the Einstein Aging Study (EAS). Alzheimer’s Association International Conference. https://alz.confex.com/alz/2025/meetingapp.cgi/Paper/110603
1. **Roque, N.**, Sliwinski, M., Katz, M., & Anderson-Hanley, C. (2023). Revolutionizing Cognitive Assessment: The Power of Digital Biomarkers and Ecologically Valid Methods. In-person oral presentation by lead-author at the Annual Scientific Meeting of the Gerontological Society of America (GSA).
1. **Roque, N.A.** (2022, August). Exploring Model-based Profiles of Adherence to a Technology-Based Cognitive Intervention. Presented in-person at the American Psychological Association Annual Conference. [**Premier Psychology Conference**]
1. **Roque, N.A.**, <u>Adamo, S.</u>*, Lago, M., Barufaldi, B. (2022, July). Modeling Quit-time Behavior in a Satisfaction of Search (SOS) Experimental Framework: The Role of Context and Experience. Presented virtually at the Medical Image Perception Society Annual Conference.
1. **Roque, N.A.** (2022, April). Implementation of Web-based Experiments: Considerations for a Live Study. Presented virtually at the Cognitive Aging Conference.
1. Harrell, E., **Roque, N.**, Boot, W., & Charness, N. (2021). Exploring Factors that Shape Adherence to Technology-Based Cognitive Interventions. Innovation in Aging, 5(Suppl 1), 843-843. [**Premier Gerontology Conference**]
1. **Roque, N. A.**, Hall, C. B., Katz, M., & Sliwinski, M. J. (2021, November). Air Pollution Exposure is Associated with Cognitive Performance: Results from the Einstein Aging Study. Virtual presentation by lead-author at the 2021 Annual Scientific Meeting of the Gerontological Society of America (GSA) conference.  Innovation in Aging, 5(Suppl 1), 138-138. [**Premier Gerontology Conference**]
1. **Roque, N. A.**, Hall, C. B., Katz, M., & Sliwinski, M. J. (2021, August). Air Pollution Exposure is Associated with Cognitive Performance: Results from the Einstein Aging Study. Virtual presentation by lead-author at the 2021 International Society for Environmental Epidemiology (ISEE) conference. In ISEE Conference Abstracts (Vol. 2021, No. 1). [**Premier International Environmental Epidemiology Conference**]
1. Boot, W., **Roque, N.**, Harrell, E., & Charness, N. (2020). Older Adults’ Adherence to Technology-Based Intervention: The Role of Messaging and Individual Differences. Virtual presentation by lead-author. Innovation in Aging, 4(Suppl 1), 555.
1. Charness, N., Souders, D., Best, R., **Roque, N.**, Yoon, J., & Stothart, C. (2020). Acceptance of Transportation Technologies by Aging Adults. Virtual presentation by lead-author. Innovation in Aging, 4(Supplement_1), 555-555.
1. Harrington, K., **Roque, N.**, Zhaoyang, R., Mogle, J., & Sliwinski, M. (2020). Loneliness and Profiles of Objective and Subjective Memory During Midlife. Virtual presentation by lead-author. Innovation in Aging, 4(Suppl 1), 565.
1. Cerino, E. S., Hyun, J., Hakun, J. G., **Roque, N. A.**, Lipton, R. B., & Sliwinski, M. J. (2020). Variability in working memory performance on mobile devices is sensitive to mild cognitive impairment: Results from the Einstein Aging Study: Neuropsychology/early detection of cognitive decline with neuropsychological tests. Virtual presentation by lead-author. Alzheimer's & Dementia, 16, e039960.
1. Sliwinski, M. J., Hakun, J. G., **Roque, N.**, Katz, M. J., Zhaoyang, R., & Lipton, R. B. (2019). Intensive ambulatory cognitive assessments in older adults: sensitivity to cognitive risk status in the Einstein Aging Study (EAS). Virtual presentation by lead-author. Alzheimer's & Dementia, 15(7), P355-P356.
1. Oravecz, Z., **Roque, N.**, & Sliwinski, M. (2020, November). Bayesian Modeling of Cognitive Impairment in the Presence of Retest Effects. Innovation in Aging, 4(Suppl 1), 566. Virtual presentation presented by lead-author at the Annual Scientific Meeting of the Gerontological Society of America (GSA). Virtual
1. **Roque, N.**, Sliwinski, M., & Ram, N. (2020, November). Questionnaire-Based Everyday Reaction Time: Reliable, Valid, and Unobtrusive Measure of Cognition. Innovation in Aging, 4(Suppl 1), 599. Virtual presentation by lead-author at Annual Scientific Meeting of the Gerontological Society of America (GSA).
1. **Roque, N.**, Ram, N., & Ong, A. (2019, January). Predicting health outcomes from time series features of affect dynamics: a machine learning approach. Presented by lead-author at the Bi-Annual World Congress Meeting of the International College of Psychosomatic Medicine (ICPM). Florence, Italy. In Psychotherapy and Psychosomatics (vol. 88, pp. 110-110). Allschwilerstrasse 10, CH-4009 Basel, Switzerland: Karger. https://www.karger.com/Article/Pdf/502467
1. Ong, A., **Roque, N.**, & Ram, N. (2019). Fragile positive affect and systemic inflammation. Presented by lead-author at the Bi-Annual World Congress Meeting of the International College of Psychosomatic Medicine (ICPM). Florence, Italy. In Psychotherapy and Psychosomatics (Vol. 88, pp. 100-100). Allschwilerstrasse 10, CH-4009 Basel, Switzerland: Karger.  https://www.karger.com/Article/Pdf/502467
1. Mason, J., Jaime, S., **Roque, N.A.**, Maharaj, A., Tenenbaum, G., & Figueroa, A. (2019, May). The effects of an acute bout of aerobic exercise on cognitive function in older adults. Presented by lead-author at the Annual Meeting of the American College of Sports Medicine (ACSM). Orlando, FL.
1. **Roque, N.A.**, Boot, W.R. (2018, May). The Development and Validation of the Mobile Device Proficiency Questionnaire in U.S. Samples. Presented at the 2018 Annual Meeting of the International Society for Gerontechnology. St. Petersburg, FL.
1. Souders, D.J., Charness, N., **Roque, N.A.**, Pham, H. (2018, April). Do Advanced Driver Assistance Systems (ADAS) improve older driver performance? Presented by lead-author at SUNY Stony Brook, Smart and Connected Community Conference. New York.
1. **Roque, N.A.**, Boot, W.R., Charness, N., Barajas, K., Dirghalli, J., Mitchum, A. (2016, July). Exploring the Comprehension of a New Traffic Signal to Promote the Safety and Awareness of Pedestrians. Presented at Human Computer Interaction International (HCII). Toronto.

### Conference Posters

1. Prieto, S., Split, M., Vito, A. N. D., Strenger, J., **Roque, N. A.**, Sliwinski, M. J., Thompson, L. I., & Kunicki, Z. J. (2025). The Impact of Stress on Cognitive Performance in Remote Smartphone-Based Assessments: Exploring Within-Person Variability. Alzheimer’s & Dementia, 21(S3), e102501. https://doi.org/10.1002/alz70857_102501
1. Sergeyev, N., Bodek, H., Moffitt, C., Andrews, H. J., Cameron, J. D., Lavin, R., **Roque, N. A.**, Ezzati, A., Lipton, R. B., & Rabin, L. A. (2025). Impact of Sociodemographic and Linguistic Factors on TICS-m Screening: Findings from the Remote-CARE Study. Alzheimer’s & Dementia, 21(S3), e106205. https://doi.org/10.1002/alz70857_106205
1. **Roque, N. A.**, Katz, M. J., Garza, A. G. D. L., Hosgood, D., & Hall, C. B. (2025). Exposures to PM2.5 in Older Adults: Differences by Cognitive Status and Age in the Einstein Aging Study. Alzheimer’s & Dementia, 21(S2), e106788. https://doi.org/10.1002/alz70856_106788
1. Cheng, K. J. G., & **Roque, N. A.** (2025). Hitting the Brakes: Driving Cessation, Cognitive Health, and the Mediating Role of Social Relationships Among Older Adults in the US. Alzheimer’s & Dementia, 21(S4), e099940. https://doi.org/10.1002/alz70858_099940
1. Anderson-Hanley, C., **Roque, N. A.**, Rogers, J., Needham, V., Panos, S., & Warner, G. (2025). Digital biomarker for assessing executive function in a remote iPACES clinical trial for mild cognitive impairment: The comparability of the electronic Stroop vs. the paper Stroop. Alzheimer’s & Dementia, 21(S3), e107788. https://doi.org/10.1002/alz70857_107788
1. Andrews, H. J., Ezzati, A., Rabin, L. A., Sergeyev, N., Bodek, H., Cameron, J. D., Moffitt, C., Lavin, R., Lipton, R. B., & **Roque, N. A.** (2025). Open-Source Development of The Remote Cognitive Aging and Alzheimer’s Disease Research R-CARE Toolbox for Advancing Remote Neuropsychological Assessment for Cohorts and Clinical Trials. Alzheimer’s & Dementia, 21(S2), e106978. https://doi.org/10.1002/alz70856_106978
1. Garza, A. G. D. L., Derby, C. A., Wang, C., **Roque, N. A.**, Katz, M. J., Lipton, R. B., & Rabin, L. A. (2025). Elucidating the Association Between Pain and Self‐Perceived Cognitive Functioning Using Daily Digital Diary Assessments: Results from the Einstein Aging Study (EAS). Alzheimer's & Dementia, 21(Suppl 9), e110543. https://doi.org/10.1002/alz70863_110543
1. Velazquez, E., & **Roque, N.** (2025). Impact of Global and Local Clutter on Visual Search Efficiency and Attentional Guidance. Journal of Vision, 25(9), 2209–2209. https://doi.org/10.1167/jov.25.9.2209
1. Nester, C.O., De Vito, A.N., Kunicki, Z.J., Strenger, J., Harrington, K.D., **Roque, N.A.**, Sliwinski, M.J., & Thompson, L.I. Subjective Cognitive Concerns and High Frequency Mobile App Based Cognitive Assessment in Older Adults: Relationship to Adherence, Satisfaction, and Cognitive Performance. Poster accepted for the Alzheimer’s Association International Conference 2024. [**Premier International Alzheimer’s Conference**]
1. **Roque, N.A.**, Sliwinski, M., Derby, C., Lipton, R.B., Buxton, O., & Katz, M. (2023). Feasibility of A Multi-Pronged, Multi-Sensor Cognitive Aging Protocol in a Diversified Cohort: Results from the Einstein Aging Study. Poster accepted for the Alzheimer’s Association International Conference 2024. [**Premier International Alzheimer’s Conference**]
1. <u>Flores-Cruz, G.</u>* & **Roque, N.** (2024, May). Eye Tracking Impacts of an Irrelevant Self-View Singleton. Poster accepted at the 2024 Vision Science Society Conference. To be presented by lead author.
1. <u>Velasquez, E.</u>* & **Roque, N.** (2024, May). Assessing The Effect of Stimuli Complexity in Web-Based Visual Foraging. Poster accepted at the 2024 Vision Science Society Conference. To be presented by lead author.
1. De Vito, A., Kunicki, Z., Britton, K., Villa, P., Strenger, J., Harrington, K., ... & Thompson, L. I. (2023). 5 Intraindividual Variability in Processing Speed on Digital Cognitive Assessments Differs by Amyloidosis Status in Cognitively Normal Older Adults. Journal of the International Neuropsychological Society, 29(s1), 217-218. [**Premier International Neuropsychology Conference**]
1. Strenger, J. R., Riera, N., Harrington, K., **Roque, N.**, Salloway, S., Sliwinski, M., & Thompson, L. I. (2023). 28 Variability in Remote, Self-Administered Assessment Performance Associated with Self-Reported Memory Perceptions Among Older Adults. Journal of the International Neuropsychological Society, 29(s1), 340-341. [**Premier International Neuropsychology Conference**]
1. DeBonis, D. G., Dunnam, M., Panos, S., Warner, G., **Roque, N.**, & Anderson-Hanley, C. (2023). 78 Examining the Association Between a Patient's Diagnosis and Occurrence of The First Error on Trails B. Journal of the International Neuropsychological Society, 29(s1), 280-280. [**Premier International Neuropsychology Conference**]
1. De Vito, A. N., Kunicki, Z.J., Emrani, S., Strenger, J., Harrington, K.D., **Roque, N.A.**, ... & Thompson, L. I. (2023). Fatigue Interacts with Amyloid Status To Predict Daily Working Memory Performance in Preclinical Alzheimer’s Disease. Alzheimer's & Dementia, 19, e080094. [**Premier International Alzheimer’s Conference**]
1. Strenger, J., Emrani, S., Kunicki, Z.J., Harrington, K.D., **Roque, N. A.**, Sliwinski, M.J., ... & Thompson, L. I. (2023). Time of day cognitive performance differences in remote, self‐administered assessments and its association with cerebral amyloidosis. Alzheimer's & Dementia, 19, e080096. [**Premier International Alzheimer’s Conference**]
1. Katz, M.J., De La Garza, A., **Roque, N.A.**, Derby, C.A., Sliwinski, M.J., Lipton, R.B., Wang, C. (2023). Feasibility, reliability and predictive validity of digital cognitive assessments in a diverse cohort of community-residing older adults. Presented in person by lead author at the 2023 Alzheimer’s Association International Conference. [**Premier International Alzheimer’s Conference**]
1. Harrington, E., Graham-Engeland, J.E., Lipton, R.B., **Roque, N.A.**, Sliwinski, M.J., Engeland, C.G. (2023). Inflammation and working memory performance in everyday life: Gender differences among older adults with and without cognitive impairment. Presented in person by lead author at the 2023 Alzheimer’s Association International Conference. [**Premier International Alzheimer’s Conference**]
1. <u>Thai, P.</u>*, <u>Flores-Cruz, G.</u>*, & **Roque, N.** (2023, October). Leveraging healthcare technology to improve patient-doctor communication. Poster presented by lead author at the 67th annual conference of the Human Factors and Ergonomics Society. Conference proceeding posted in the Proceedings of the Human Factors and Ergonomics Society, 67.
1. <u>Flores-Cruz, G.</u>*, <u>Hinkle, S.</u>*, **Roque, N.**, & Mouloua, M. (2023). ChatGPT as the ultimate travel buddy or research assistant: a study on perceived attitudes and usability. Conference proceeding posted in the Proceedings of the Human Factors and Ergonomics Society, 67.
1. <u>Flores-Cruz, G.</u>*, **Roque, N.** (2023, June). Perception of Environmental Risk: Comparing Mental Models of Indoor and Outdoor Air Pollution. Poster presented at the 35th annual conference of the International Society for Environmental Epidemiology.
1. **Roque, N.**, & <u>Adamo, S.</u>* (2023). Modeling Observer Search Termination in a Subsequent Search Misses (SSM) Experimental Framework: The Role of Experience. Poster presented at the 23rd Annual conference of the Vision Sciences Society. Journal of Vision, 23(9), 5936-5936.
1. **Roque, N.A.**, <u>Ferguson, I.</u>*, Saulnier, E.T., Anderson-Hanley, C. Trail Making for electronic touchscreen self-administration (eTrails) as used in the remote iPACES neuro-exergaming trial for Mild Cognitive Impairment (MCI): An initial validation report. Submitted to Alzheimer’s Association International Conference 2022. Presented Virtually. [**Premier International Alzheimer’s Conference**]
1. **Roque, N.A.**, Anderson-Hanley, C. Saulnier, E.T. (2021, October). Translating the Paper Stroop Task for Repeated Administration as an Electronic Stroop (eStroop) Task on Mobile Devices for a Remote Exercise Intervention for Mild Cognitive Impairment (MCI). (virtual) 11th edition of the International Conference on Frailty and Sarcopenia Research (ICFSR 2021).
1. <u>Dalterio, C.</u>*, <u>Ferguson, I.</u>*, Nath, K., **Roque, N.A.**, Arciero, P., Anderson-Hanley, C. (2021, October). Biomarker and cognitive effects of single bouts of moderate-intensity neuro-exergaming, high-intensity interval training (HIIT), and fasted exercise for mild cognitive impairment: A case study of serial interventions. Presented by lead author at the (virtual) 11th edition of the International Conference on Frailty and Sarcopenia Research (ICFSR 2021).
1. Harrell, E., **Roque, N.**, Boot, W., & Charness, N. (2021). Exploring Factors that Shape Adherence to Technology-Based Cognitive Interventions. Innovation in Aging, 5(Suppl 1), 843-843. Presented by the lead author at the (virtual) Annual Scientific Meeting of the Gerontological Society of America (GSA) [**Premier Gerontology Conference**]
1. **Roque, N.**, & Harrell, E. (2020, November). Give People What They Want, Feedback: Older Adult Perceptions on Cognitive Training Features to Increase Engagement. Innovation in Aging, 4(Suppl 1), 411. Presented at the (virtual) Annual Scientific Meeting of the Gerontological Society of America (GSA). [**Premier Gerontology Conference**]
1. Harrell, E., & **Roque, N.** (2020, November). I'd Rather Be...: Activities Older Adults Reported Leading to Decreased Engagement With Cognitive Training. Innovation in Aging, 4(Suppl 1), 325. Presented by the lead author at the (virtual) Annual Scientific Meeting of the Gerontological Society of America (GSA). [**Premier Gerontology Conference**]
1. **Roque, N.**, & Harrell, E. (2020, October). Give the People What they Want, Feedback: Older adult perceptions of cognitive training features. Innovation in Aging, 4(Suppl 1), 411. Presented at the (virtual) Annual Scientific Meeting of the International Society for Gerontechnology (ISG). Gerontechnology, 19(0), 1-1. https://doi.org/10.4017/gt.2020.19.s.70037 [**Premier Gerontology Conference**]
1. **Roque N.A.**, Boot, W.R., (2018, November). A New Scale for Assessing Older Adults' Wireless Network Proficiency: The Wireless Network Proficiency Questionnaire. Presented at the Annual Scientific Meeting of the Gerontological Society of America (GSA). Boston, MA. [**Premier Gerontology Conference**]
1. Lebeau, J.C., Mason, J., **Roque, N.A.**, Razon, S., & Tenenbaum, G. (2018, June). The Effects of Acute Exercise on Driving Performance and Executive Functions in Healthy Older Adults. Presented at North American Society for Psychology of Sport and Physical Activity’s 51st Annual Meeting in Denver, Colorado.
1. Mason, J., **Roque N.A.**, Maharaj A., Salvador, J., Figueroa, A. (2018, June). Exploring the effects of life-long aerobic exercise on cognitive function, driving performance, and cardiovascular health. Poster presented at American College of Sports Medicine’s 65th Annual Meeting in Minneapolis, Minnesota.
1. **Roque N.A.**, Boot, W.R., (2018, May). Pupillometry as a window into the content and strength of attention sets. Presented at the 18th Annual Meeting of the Vision Sciences Society. St. Petersburg Beach, FL. https://jov.arvojournals.org/article.aspx?articleid=2700102
1. Andringa, R., **Roque N.A.**, Boot, W.R., (2018, May). Exploring the Effect of Task Complexity, Presentation, and Input Device on the Near-Hands Advantage. Presented at the 18th Annual Meeting of the Vision Sciences Society. St. Petersburg Beach, FL. https://jov.arvojournals.org/article.aspx?articleid=2699638
1. **Roque N.A.**, Harrell, E., Wright, T.J., Boot, W.R., (2018, May). Exploring Visual Search as a Paradigm for Predicting Medication Errors. Presented at Cognitive Aging Conference 2018. Atlanta, GA.
1. Ospina J.*, Yazbec, A., **Roque, N.A.**, Borovsky, A. (2017, April). Pupillometry measures highlight the timing of cognitive effort during linguistic adaptation. Presented at CUNY 2017 Conference on Human Sentence Processing.
1. **Roque N.A.**, Wright T.J., Boot W.R. (2016, May) Do different attention capture paradigms measure different types of capture? Presented at the 16th Annual Meeting of the Vision Sciences Society. St. Petersburg Beach, FL. https://jov.arvojournals.org/article.aspx?articleid=2550984
1. **Roque N.A.**, Boot W.R. (2016, April) Mobile Device Proficiency Questionnaire (MDPQ): Assessing mobile smart device proficiency among seniors. Presented at Cognitive Aging Conference 2016. Atlanta, GA.
1. **Roque N.A.**, Boot W.R. (2015, November). Do Different Attention Capture Paradigms Measure Different Types of Capture? Presented at the 23rd Object Perception, Attention and Memory (OPAM) Workshop. Chicago, IL.
1. **Roque N.A.**, Wright T.J., Boot W.R. (2015, May). Exploring Visual Search as a Paradigm to Study Medication Errors. Presented at the 15th Annual Meeting of the Vision Sciences Society. St. Petersburg Beach, FL. https://jov.arvojournals.org/article.aspx?articleid=2433979
1. **Roque N.A.**, Boot, W.R. (2014, May). Exploring the Relationship between Object-Based Attention Effects and Object Realism. Poster presented at the 14th Annual Meeting of the Vision Sciences Society. St. Petersburg Beach, FL. https://jov.arvojournals.org/article.aspx?articleid=2144943
1. Driscoll K.A., Johnson S.B., Gill E., Pizzi A., **Roque N.A.**, Sorrentino E., … (2012, August) “Grading” Type 1 Diabetes Knowledge: How Well Do Children and Parents Perform? Presented at the 120th Annual Convention of the American Psychological Association. Orlando, FL.

### University / Department / Center: Oral Presentations

1. **Roque N.A.** (2023, October). Breathe Well, Age Well: A Comprehensive Look at Air Quality for Older Adults. Presented at the Penn State Center for Healthy Aging Colloquium.
1. **Roque N.A.** (2023, March). Reproducible Data Science. Workshop presentation for UCF Research IT. Workshop event listing: https://events.ucf.edu/event/2891771/reproducible-data-science/
1. **Roque N.A.** (2023, March). Qualtrics for Research Data Collection. Workshop presentation for UCF Research IT. Workshop event listing: https://events.ucf.edu/event/2819983/qualtrics-for-research-data-collection/
1. **Roque N.A.** (2021, September). Introduction to Data Wrangling & Visualization in R: Exploring the Google Mobility Dataset. Workshop presentation for UCF HFC Doctoral Program Brown bag series. Workshop materials open-sourced: https://github.com/nelsonroque/contextlab_intro_datascience
1. **Roque N.A.** (2019, November). Using Model-Based Cluster Analyses of Cognitive Performance to Unpack Differences in Psychosocial Risk Factors. Presentation for Pennsylvania State University’s Center for Health Aging, Aging SIG.
1. **Roque N.A.** (2018, March). tsfeaturex: Automating the Extraction of Time Series Features. Presentation for Pennsylvania State University’s QuantDev Brown Bag Lecture Series.
1. **Roque N.A.** (2018, April). Reliably measuring attention capture: Challenges and new approaches. Presentation for FSU Psychology’s Graduate Research Day.
1. **Roque N.A.** (2017, April). Exploring visual search as a paradigm for predicting medication errors. Presentation for FSU Psychology’s Graduate Research Day.
1. **Roque N.A.** (2016, April). Do different attention capture paradigms measure different types of capture? Presentation for FSU Psychology’s Graduate Research Day.
1. **Roque N.A.** (2016, March). Exploring visual search as a paradigm for studying medication errors. Research sharing luncheon held by the FSU Fellows Society.
