## Peer-Reviewed Articles

Supervised students, postdocs, and other mentees are <u>underlined</u>.

::: {.publication-list}

1. **Roque, N. A.**, Hosgood, H. D., & Hall, C. B. (2026). The importance of accurate indoor air quality assessment in the aging and dementia population. *Journal of Alzheimer’s Disease*, 109(2), 630-632, 13872877251396928. https://doi.org/10.1177/13872877251396928
1. <u>Shaleha, R.</u>*, **Roque, N.**, <u>Andrews, H.</u>*, <u>Calfee, K.</u>*, & Lee, S. (2026). Screen use measurement tools: A mapping of instruments, gaps, and future directions. *Cyberpsychology, Behavior, and Social Networking*, 29(3), 140–150. https://doi.org/10.1177/21522715261417288
1. <u>Shaleha, R. R. A.</u>, & **Roque, N. A.** (2026). Screen time in context: Toward a theoretical model of digital engagement across the lifespan. Developmental Psychology. Advance online publication. https://doi.org/10.1037/dev0002202
1. **Roque, N. A.**, <u>Andrews, H.</u>, & Santos-Lozada, A. R. (2025). Identifying air quality monitoring deserts in the United States. Proceedings of the National Academy of Sciences, 122(17), e2425310122. https://doi.org/10.1073/pnas.2425310122
1. Doheny, M. M., **Roque, N. A.**, & Lighthall, N. R. (2025). Effects of maximum and minimum offers on reciprocity and trust perceptions during economic decision-making. *Frontiers in Cognition*, 4. Fcogn.2025.1576987. https://doi.org/10.3389/fcogn.2025.1576987
1. Katz, M. J., Johns, T. S., Martin, M. M., Burgess, A., Claris, V., Volda, G. S., **Roque, N.**, Shaw, P. A., Hyun, N., Hakun, J. G., Pavlovic, J. M., Wylie-Rosett, J., Sliwinski, M. J., & Mossavar-Rahmani, Y. (2025). Recruitment of mid-life adults to a randomized clinical trial: The multicultural healthy diet study to reduce cognitive decline and Alzheimer’s disease risk. *Alzheimer’s & Dementia: Translational Research & Clinical Interventions*, 11(4), e70174. https://doi.org/10.1002/trc2.70174
1. **Roque, N.**, & Felt, J. (2025). Acceptability of Active and Passive Data Collection Methods for Mobile Health Research: Cross-Sectional Survey of an Online Adult Sample in the United States. *JMIR Formative Research*, 9(1), e64082. https://doi.org/10.2196/64082
1. <u>Shaleha, R.</u>, & **Roque, N.** (2025). From screens to cognition: A scoping review of the impact of screen time on cognitive function in midlife and older adults. *Digital health*, 11, 20552076251343989. https://doi.org/10.1177/20552076251343989
1. Oravecz, Z., Vandekerckhove, J., Hakun, J.G., Kim, S.H., Katz, M.J., Wang, C., Lipton, R.B., Derby, C.A., **Roque, N.A.** and Sliwinski, M.J., (2025). Computational phenotyping of cognitive decline with retest learning. *The Journals of Gerontology, Series B: Psychological Sciences and Social Sciences*, 80(7), gbaf030. https://doi.org/10.1093/geronb/gbaf030
1. García de la Garza, Á., Nester, C., Wang, C., Mogle, J., **Roque, N.**, Katz, M., CA Derby, RB Lipton,  & Rabin, L. (2025). Enhanced associations between subjective cognitive concerns and blood-based AD biomarkers using a novel EMA approach. *Alzheimer's Research & Therapy*, 17(1), 82, s13195-025-01720-y. https://doi.org/10.1186/s13195-025-01720-y
1. Nester, C. O., De Vito, A. N., Prieto, S., Kunicki, Z. J., Strenger, J., Harrington, K. D., **Roque, N.A.**, Sliwinski, M.J., Rabin, L.A., & Thompson, L. I. (2025). Association of Subjective Cognitive Concerns With Performance on Mobile App–Based Cognitive Assessment in Cognitively Normal Older Adults: Observational Study. <i>JMIR Aging</i>, 8, e64033. https://doi.org/10.2196/64033
1. <u>Shaleha, R.R.A.</u>*, & **Roque, N.** (2024). Cognitive Performance in the Digital Era: Generational Differences, Stress, and Distraction's Impact on Cognitive Performance. <i>International Journal of Cyber Behavior, Psychology and Learning (IJCBPL)</i>, 14(1), 1-13, IJCBPL.341788. https://doi.org/10.4018/IJCBPL.341788
1. <u>Adamo, S.H.</u>*, **Roque, N.**, Barufaldi, B., Schmidt, J., Mello-Thoms, C., & Lago, M. (2023). Assessing satisfaction of search in virtual mammograms for experienced and novice searchers. <i>Journal of Medical Imaging</i>, 10(S1), S11917-S11917. https://doi.org/10.1117/1.JMI.10.S1.S11917
1. Harrell, E. R., **Roque, N.A.**, & Boot, W. R. (2023). Comparing the effectiveness of two theory-based strategies to promote cognitive training adherence. <i>Journal of Experimental Psychology: Applied</i>, 29(4), 782, xap0000485. https://doi.org/10.1037/xap0000485
1. <u>Hyun, J.</u>, Katz, M. J., Derby, C. A., **Roque, N.**, Muñoz, E., Sliwinski, M. J., Lovasi G. S. & Lipton, R. B. (2023). Availability of healthy foods, fruit and vegetable consumption, and cognition among urban older adults. *BMC geriatrics*, 23(1), 302, s12877-023-04003-z. https://doi.org/10.1186/s12877-023-04003-z
1. Thompson, L.I., Kunicki, Z.J., Emrani, S., Strenger, J., De Vito, A.N., Britton, K.J., Dion, C., Harrington, K.D., **Roque, N.**, Salloway, S. and Sliwinski, M.J., (2023). Remote and in‐clinic digital cognitive screening tools outperform the MoCA to distinguish cerebral amyloid status among cognitively healthy older adults. *Alzheimer's & Dementia: Diagnosis, Assessment & Disease Monitoring*, 15(4), e12500. https://doi.org/10.1002/dad2.12500
1. Hakun, J. G., **Roque, N.A.**, Gerver, C.R., & Cerino, E.S. (2023). Ultra-brief Assessment of Working Memory Capacity: Ambulatory Assessment Study Using Smartphones. *JMIR Formative Research*, 7, e40188. https://doi.org/10.2196/40188
1. <u>Wan, X.</u>*, Lighthall, N. R., & **Roque, N.** (2024). Predictors of Technology Use: Evidence from Elite Older Adults. *Activities, Adaptation & Aging*, 48(4), 648-669, 01924788.2023.2282276. https://doi.org/10.1080/01924788.2023.2282276
1. Harrington, K. D., **Roque, N.A.**, Strenger, J., Correia, S., Salloway, S. P., Sliwinski, M. J., & Thompson, L. I. (2022). Loneliness and subjective cognitive impairment in preclinical Alzheimer’s disease and healthy aging. *Alzheimer's & Dementia*, 18, e069279. https://doi.org/10.1002/alz.069279
1. Nicosia J., Wang B., Aschenbrenner A.J., Sliwinski, M.J., Yabiku, S., **Roque, N.A.**, Germine, L.T., Bateman, R.J., Morris, J.C., Hassenstab, J. (2022). To BYOD or not: Are device latencies important for bring-your-own-device (BYOD) smartphone cognitive testing? *Behavior research methods*, 55(6), 2800-2812, s13428-022-01925-1. https://doi.org/10.3758/s13428-022-01925-1
1. Johnston, E. A., **Roque, N.A.**, Cole, B. H., Flanagan, M. P., Kris-Etherton, P. M., & Petersen, K. S. (2022). A Pilot Study of the Effect of Evening Almond Butter Consumption on Overnight and Fasting Interstitial Glucose. *Diabetology*, 3(4), 502-513, 3040038. https://doi.org/10.3390/diabetology3040038 [**Premier Diabetes Journal - Chosen for Cover Story**]
1. Hoogendoorn, C. J., Qin, J., Wang, C., **Roque, N.**, Laurenceau, J. P., Katz, M. J., Derby, C. A., Lipton, R. B.,  & Gonzalez, J. S. (2022). Depressive symptoms mediate the relationship between diabetes and cognitive performance in a community-based sample of older adults. *Journal of Diabetes and its Complications*, 36(7), 108183. https://doi.org/10.1016/j.jdiacomp.2022.108183
1. Thompson, L. I., Harrington, K. D., **Roque, N.**, Strenger, J., Correia, S., Jones, R. N., Salloway, S.,  & Sliwinski, M. J. (2022). A highly feasible, reliable, and fully remote protocol for mobile app‐based cognitive assessment in cognitively healthy older adults. *Alzheimer's & Dementia: Diagnosis, Assessment & Disease Monitoring*, 14(1), e12283. https://doi.org/10.1002/dad2.12283
1. Pasquini, G., Ferguson, G., Bouklas, I., Vu, H., Zamani, M., Zhaoyang, R., Harrington, K.D., **Roque, N.A.**, Mogle, J., Schwartz, H.A., & Scott, S. B. (2022). The where and when of COVID-19: Using ecological and Twitter-based assessments to examine impacts in a temporal and community context. *PloS one*, 17(2), e0264280. https://doi.org/10.1371/journal.pone.0264280 [**Premier Open Access Journal; IF = 3.75**]
1. He, Z., Tian, S., Singh, A., Chakraborty, S., Zhang, S., Lustria, M. L. A., Charness, N., **Roque, N.A.**, Harrell, E. & Boot, W. R. (2022). A Machine-Learning-Based Approach for Predicting Older Adults’ Adherence to Technology-Based Cognitive Training. *Information Processing & Management*, 59(5), 103034. https://doi.org/10.1016/j.ipm.2022.103034 [**Premier International Journal of Information Sciences; IF = 6.222**]
1. Harrell, E. R., **Roque, N.A.**, Boot, W. R., & Charness, N. (2021). Investigating message framing to improve adherence to technology-based cognitive interventions. *Psychology and aging*, 36(8), 974, pag0000629. https://doi.org/10.1037/pag0000629 [**Premier Adult Development and Aging Journal; IF = 3.34**]
1. Yang, C. H., Hakun, J. G., **Roque, N.**, Sliwinski, M. J., & Conroy, D. E. (2021). Mindful walking and cognition in older adults: A proof of concept study using in-lab and ambulatory cognitive measures. *Preventive Medicine Reports*, 23, 101490. https://doi.org/10.1016/j.pmedr.2021.101490
1. Gray, N., Yoon, J. S., Charness, N., Boot, W. R., **Roque, N.A.**, Andringa, R., Harrell, E. R., Lewis, K. G., & Vitale, T. (2021). Relative effectiveness of general versus specific cognitive training for aging adults. *Psychology and aging*, 37(2), 210–221, pag0000663. https://psycnet.apa.org/doi/10.1037/pag0000663 [**Premier Adult Development and Aging Journal; IF = 3.34**]
1. Cerino, E.S., Katz, M.J., Wang, C., Qin, J., Gao, Q., Hyun, J., Hakun, J.G., **Roque, N.A.**, Derby, C.A., Lipton, R.B., & Sliwinski, M.J. (2021). Variability in cognitive performance on mobile devices is sensitive to mild cognitive impairment: Results from the Einstein Aging Study. *Frontiers in Digital Health*, 3, 758031. https://doi.org/10.3389/fdgth.2021.758031
1. **Roque, N.A.**, & Boot, W. R. (2020). A New Tool for Assessing Older Adults’ Wireless Network Proficiency: The Wireless Network Proficiency Questionnaire. *Journal of Applied Gerontology*, 40(5), 541-546, 0733464820935000 https://doi.org/10.1177/0733464820935000
1. Emihovich, B., **Roque, N.A.**, & Mason, J. (2020). Can Video Gameplay Improve Undergraduates' Problem-Solving Skills?. *International Journal of Game-Based Learning (IJGBL)*, 10(2), 1-18, 2020040102. https://doi.org/10.4018/ijgbl.2020040102
1. Lebeau, J.-C., Mason, J. R., **Roque, N.A.**, Tenenbaum, G. (2020). The effects of acute exercise on driving and executive functions in healthy older adults. *International Journal of Sport and Exercise Psychology*, 20(1), 283-301. https://doi.org/10.1080/1612197X.2020.1849353
1. Mason, J. R., Tenenbaum, G., Jaime, S., **Roque, N.A.**, Maharaj, A., Figueroa, A. (2020). Arterial Stiffness and Cardiorespiratory Fitness Are Associated With Cognitive Function in Older Adults. *Behavioral Medicine*: 1-12, 48(1), 54-65, 08964289.2020.1825921. https://doi.org/10.1080/08964289.2020.1825921
1. Boot, W. R., Andringa, R., Harrell, E. R., Dieciuc, M. A., & **Roque, N. A.** (2020). Older adults and video gaming for leisure: Lessons from the Center for Research and Education on Aging and Technology Enhancement (CREATE). *Gerontechnology*, 19(2),  gt.2020.19.2.006.00. https://doi.org/10.4017/gt.2020.19.2.006.00
1. **Roque, N.A.**, Ram, N. (2019). tsfeaturex: An R Package for Automating Time Series Feature Extraction. *Journal of Open Source Software*, 4(37), 1279, https://doi.org/10.21105/joss.01279
1. Yoon, J. S., **Roque, N.A.**, Andringa, R., Harrell, E. R., Lewis, K. G., Vitale, T., Charness, N.,  & Boot, W. R. (2019). Intervention comparative effectiveness for adult cognitive training (ICE-ACT) trial: rationale, design, and baseline characteristics. *Contemporary Clinical Trials*, 78, 76-87,  2019.01.014. https://doi.org/10.1016/j.cct.2019.01.014. [**Premier International Clinical Trials Journal; IF=2.226**]
1. Dieciuc, M., **Roque, N.A.**, Boot, W.R. (2019). The spatial dynamics of mouse-tracking reveal that attention capture is stimulus-driven rather than contingent upon top-down goals. *Journal of Experimental Psychology: Human Perception and Performance*, 45(10), 1285, xhp0000671. https://doi.org/10.1037/xhp0000671
1. Souders, D. J., Charness, N., **Roque, N.A.**, & Pham, H. (2019). Aging: Older Adults’ Driving Behavior Using Longitudinal and Lateral Warning Systems. *Human Factors*, 62(2), 229-248, 0018720819864510. https://doi.org/10.1177/0018720819864510 [**Premier Human Factors Journal; IF=3.165**]
1. Tinker, A., Fozard, J., Kearns, W., Mihailidis, A., Atoyebi, O., Bailey, A., Bet, P., Lapierre, N., Neubauer, N., **Roque, N.A.**, Vermeer, Y., Taipale, V. (2018). Twelve years of ISG masterclasses: Past, Present, and Future. *Gerontechnology: international journal on the fundamental aspects of technology to serve the ageing society*, 17(4), 232, gt.2018.17.4.004.00. https://doi.org/10.4017/gt.2018.17.4.004.00  – Note, author list for junior scientists organized alphabetically.
1. Wright, T. J., **Roque, N.A.**, Boot, W. R., & Stothart, C. (2018). Attention capture, processing speed, and inattentional blindness. *Acta Psychologica*, 190, 72-77, 2018.07.005. https://doi.org/10.1016/j.actpsy.2018.07.005
1. Andringa, R., Boot, W.R., **Roque, N.A.**, & Ponnaluri, S. (2018). Hand proximity effects are fragile: a useful null result. *Cognitive Research: Principles and Implications*, 3(1), 7, s41235-018-0094-7. https://doi.org/10.1186/s41235-018-0094-7
1. Multilab Direct Replication Team, including Boot, W.R., Andringa, R., **Roque, N.A.**, & Harrell, E.R. (2018). Registered replication report: Dijksterhuis & van Knippenberg (1998). *Perspectives on Psychological Science*, 1-38.
1. **Roque, N. A.**, & Boot, W. R. (2018). A new tool for assessing mobile device proficiency in older adults: the mobile device proficiency questionnaire. *Journal of Applied Gerontology*, 37(2), 131-156, 0733464816642582. https://doi.org/10.1177/0733464816642582
1. Dieciuc, M., **Roque, N. A.**, & Folstein, J. R. (2017). Changing similarity: Stable and flexible modulations of psychological dimensions. *Brain Research*, 1670, 208-219, 2017.06.026. https://doi.org/10.1016/j.brainres.2017.06.026
1. Souders, D. J., Boot, W. R., Blocker, K., Vitale, T., **Roque, N. A.**, & Charness, N. (2017). Evidence for narrow transfer after short-term cognitive training in older adults. *Frontiers in Aging Neuroscience*, 9, 41, fnagi.2017.00041. https://doi.org/10.3389/fnagi.2017.00041
1. **Roque, N.A.**, Wright, T. J., & Boot, W. R. (2016). Do different attention capture paradigms measure different types of capture?. *Attention, Perception, & Psychophysics*, 78, s13414-016-1117-4. https://doi.org/10.3758/s13414-016-1117-4
1. **Roque, N.A.**, & Boot, W. R. (2015). Exploring the relationship between object realism and object-based attention effects. *Acta Psychologica*, 160, 178-183, 2015.07.014. https://doi.org/10.1016/j.actpsy.2015.07.014 [**International Journal of Psychonomics; IF=1.380**]

:::
