## Research Funding

### Current & Pending External Research Funding

| Years | Role | Sponsor | Project | Total Costs |
|:------|:-----|:--------|:--------|------------:|
| **2026–2027** | **Co-Investigator** | The Peanut Institute Foundation | Peanut butter, glycemic control, cognition, and cardiovascular health | **$290,000** |
| **2025–2030** | **Co-Investigator** | NIH/NIA | THE NIH PRECISION BRAIN HEALTH NETWORK: Open and Inclusive Measurement of Neuropsychological Change for AD/ADRD Primary Prevention Trials (U24AG092760) | **$39,000,000*** |
| **2025–2030** | **Co-Investigator** | NIH/NIA | Advancing Mobile Monitoring of Intraindividual Change in Alzheimer’s Disease and Related Dementias: Building an Open and Inclusive Infrastructure (U19AG087932) | **$19,844,799*** |
| **2023–2028** | **Subaward PI** | NIH/NIA | Validation of the Remote CARE Toolbox for Diverse Populations (R01AG080635) | **$868,564** |
| **2022–2027** | **Co-PI** | NIH/NIA | Einstein Aging Study: Air Pollution and Cognitive Function (P01AG003949) | **$911,768** |
| **2022–2027** | **Core Leader / Subaward PI** | NIH/NIA | Einstein Aging Study: Technology & Data Management Core (P01AG003949) | **$1,696,559** |
| **2022–2024** | **Subaward PI** | NIH/NIA | Perceived Ethnic Discrimination and Cognitive Function (R21AG078846) | **$90,232** |
| **2022–2023** | **Subaward PI** | NIH/NIA | Mobile Monitoring of Cognitive Change (M2C2; U2CAG060408) | **$50,000** |
| **2021–2022** | **Subaward PI** | Proactive Life, Inc. | Multi-modal Therapy to Improve Sleep and Cognition (R44AG056250) | **$14,685** |
| **2020–2022** | **PI** | NIH/NIA | Investigating Medication Errors in Daily Life (R03AG067009) | **$149,000** |

\* Multi-project infrastructure award. Serves as Co-Core Leader for the Data Management & Analytics Core.

### Funding Summary

- Principal Investigator on an NIH R03 award.
- Principal Investigator on four NIH subawards.
- Co-Principal Investigator on the Einstein Aging Study Program Project (P01) - Project 3, Air Quality and Cognition.
- Core Leader on the Einstein Aging Study Technology & Data Management Core.
- Co-Core Leader on recently funded NIH U24 and U19 infrastructure awards
- Co-Investigator on a foundation-funded clinical nutrition study.