## Student and Postdoctoral Mentorship

### Postdoctoral & Career Development (K Awards & Fellowships) Scholars

| Mentee | Award | Years | Role | Status |
|---------|-------|------:|------|--------|
| Stephen Adamo | K99/R00 | 2023–Present | Consultant | Active |
| Jinshil Hyun | K99/R00 | 2023–Present | Consultant | Active |

### Ph.D. Dissertations Chaired

| Student | Year | Department | University | Current Position |
|---------|-----:|------------|------------|------------------|
| Rinanda Shaleha | 2026 | Human Development & Family Studies | Penn State | Assistant Professor, Indonesia University of Education (Universitas Pendidikan Indonesia)
| Liujing Xie | starting Fall 2026 | Human Development & Family Studies | Penn State | 

### Graduate Committee Membership (Non-Chair)

| Student | Degree | Department | University | Role |
|---------|--------|------------|------------|------|
| Alexa Allan | Ph.D. | Human Development & Family Studies | Penn State | Committee Member |
| Jordan Sasser | Ph.D. | Psychology | University of Central Florida| Committee Member |
| John Duany | Ph.D. | Psychology | University of Central Florida| Committee Member |
| Alexander Arca | Ph.D. | Psychology | University of Central Florida| Committee Member |
| Gabriela Flores-Cruz | Ph.D. | Psychology | University of Central Florida| Committee Member |

### Undergraduate Research & Honors Theses

- N=4 Successfully chaired Honors Theses at University of Central Florida
- N=1 successful honors thesis as committee member
- N=13 Undergraduate students supervised for research activities for 1 or more semesters.