### Scientific Outreach

- RELATED TO: Roque, N. A., Andrews, H., & Santos-Lozada, A. R. (2025). Identifying air quality monitoring deserts in the United States. *Proceedings of the National Academy of Sciences, 122*(17), e2425310122.
    - Dzombak, Rebecca. 2025. "Almost Half of Americans Breathe Unhealthy Air, Report Finds." *The New York Times*. https://www.nytimes.com/2025/04/23/climate/american-lung-association-air-report.html
    - "Farming Through the Haze and Air Quality Concerns - Morning Ag Clips." https://www.morningagclips.com/farming-through-the-haze-and-air-quality-concerns/
    - Magazine, Undark. 2025. "Wildfires Are Challenging Air Quality Monitoring Infrastructure." *Ars Technica*. https://undark.org/2025/07/04/wildfires-aqi-infrastructure/
    - King, Jesse. 2025. "Bard College Expands Hudson Valley Air Monitoring Initiative, Details Findings in Kingston." *WAMC*. https://www.wamc.org/news/2025-06-30/bard-college-expands-hudson-valley-air-monitoring-initiative-details-findings-in-kingston
    - Kelly, Sharon. 2025. "As Trump Unwinds Federal Oversight, States Become Battlegrounds for Environmental Data." *DeSmog*. https://www.desmog.com/2025/06/11/as-trump-unwinds-federal-oversight-states-become-battlegrounds-for-environmental-data/
    - "Environmental Groups Sue over Louisiana's Ban on Community Air Monitoring." 2025. *Yahoo News*. https://www.yahoo.com/news/environmental-groups-sue-over-louisiana-100057123.html
    - Newsource, C. N. N. 2025. "How Many Americans Are Breathing Unhealthy Air?" *KION Central Coast*. https://kioncentralcoast.com/cnn-regional/2025/04/28/how-many-americans-are-breathing-unhealthy-air/
    - Newsource, C. N. N. 2025. "How Many Americans Are Breathing Unhealthy Air?" *KVIA*. https://kvia.com/cnn-regional/2025/04/28/how-many-americans-are-breathing-unhealthy-air/
    - "Es seguro respirar el aire? 50 millones en EE. UU. en riesgo." 2025. https://noticiasdelatierra.com/que-tan-seguro-es-respirar-el-aire-50-millones-de-personas-en-ee-uu-no-lo-saben/
    - Hawkins, J. 2025. "Almost Half of Americans Breathe Unclean Air, and It's Only Getting Worse." *BGR*. https://www.bgr.com/science/almost-half-of-americans-breathe-unclean-air-and-its-only-getting-worse/
    - Douglas, Erin. 2025. "Air Quality Is Getting Worse in Coastal New England." *Boston Globe* (Online). https://www.proquest.com/docview/3193727979/citation/7CAC9A9C28804CDCPQ/5
    - Lomte, Tarun Sai. 2025. "Study Pinpoints Vast 'Air Quality Deserts' across Nearly 60% of US Counties." *News-Medical*. https://www.news-medical.net/news/20250424/Study-pinpoints-vast-air-quality-deserts-across-nearly-6025-of-US-counties.aspx
    - Bennett, P. 2025. "Nearly Half of U.S. Population Breathes Unhealthy Air, American Lung Association Warns." *EcoWatch*. https://www.ecowatch.com/air-pollution-exposure-us-population-2025.html
    - Facher, Lev. 2025. "Over Half of U.S. Counties Have No System in Place for Monitoring Air Quality." *STAT*. https://www.statnews.com/2025/04/23/health-news-air-pollution-fda-food-dye-measles-texas-update-morning-rounds/
    - Gopal, Keerti. 2025. "Nearly Half of Americans Are Breathing Unhealthy Air as Pollution Exposure Numbers Reach Decade High." *Inside Climate News*. https://insideclimatenews.org/news/23042025/american-lung-association-unhealthy-air-report-pollution-exposure/
    - "Millions of Americans Live in Areas without Air Quality Monitoring." *Earth.com*. https://www.earth.com/news/millions-of-americans-live-in-areas-without-air-quality-monitoring/
    - Bioengineer. 2025. "Just How Safe Is the Air We Breathe? Find out What 50 Million Americans Are Missing." *BIOENGINEER.ORG*. https://bioengineer.org/just-how-safe-is-the-air-we-breathe-find-out-what-50-million-americans-are-missing/
    - "How Safe Is the Air to Breathe? 50 Million People in the US Do Not Know." *EurekAlert!* https://www.eurekalert.org/news-releases/1081150
    - "How Safe Is the Air to Breathe? 50 Million People in the US Do Not Know." *ScienceDaily*. https://www.sciencedaily.com/releases/2025/04/250421162612.htm
    - "Millions in the US Live without Local Air Quality Monitoring." *MSN*. https://www.msn.com/en-gb/news/world/millions-in-the-us-live-without-local-air-quality-monitoring/ar-AA1DlSKn
    - DNYUZ. 2025. "Almost Half of Americans Breathe Unhealthy Air, Report Finds." https://dnyuz.com/2025/04/23/almost-half-of-americans-breathe-unhealthy-air-report-finds/
    - "50 Million Live in U.S. Counties without Air Quality Monitoring." *Laboratory Equipment*. https://www.laboratoryequipment.com/618975-50-Million-Live-in-U-S-Counties-without-Air-Quality-Monitoring/
    - News, Mirage. "50 Million Americans Unaware of Air Quality Safety." *Mirage News*. https://www.miragenews.com/50-million-americans-unaware-of-air-quality-1447394/
    - SCIENMAG. 2025. "Just How Safe Is the Air We Breathe? Find out What 50 Million Americans Are Missing." *Science*. https://scienmag.com/just-how-safe-is-the-air-we-breathe-find-out-what-50-million-americans-are-missing/
    - State, Penn. 2025. "Millions in the US Live without Local Air Quality Monitoring." *News-Medical*. https://www.news-medical.net/news/20250421/How-Safe-Is-The-Air-To-Breathe-50-Million-People-In-The-US-Do-Not-Know.aspx
    - Wagner, Aaron, and Pennsylvania State University. "How Safe Is the Air to Breathe? 50 Million People in the US Don't Know." https://phys.org/news/2025-04-safe-air-million-people-dont.html

**Scientific and professional outreach**

- May 2025. Stavanger, Norway. International Joint Programme - Neurodegenerative Disease Research (JPND) Working Group Lead; leading two writing groups in producing a guidelines paper and systematic review.
- 2015, 2018. Judge. Capital Regional Science and Engineering Fair, Tallahassee, FL. Judged student poster presentations and participated in award selection.

**Public commentary**

- Penn State Outreach, featured Assistant Professor Nelson Roque, discussing healthy and unhealthy screen time during Screen Free Week. (n.d.). "Good and bad screen time for Screen Free Week | YouTube. https://www.youtube.com/watch?v=Rr7892IxZQA
- Roque, N. A., provided commentary on the potential impact of fireworks on human health. (2022, December). "How Do Fireworks Affect the Air We Breathe? We Answer Key Questions about the Pollution They Generate." https://www.univision.com/noticias/fuegos-artificiales-contaminacion-aire-respiramos-preguntas-clave
- Roque, N. A., provided commentary on the state of detecting cognitive changes. (2019, December). "If Dementia Can't Be Prevented, Can It at Least Be Detected Early?" https://qz.com/1754544/detecting-dementia-early-could-the-key-to-a-cure/
- Roque, N. A., provided audio commentary on the state of assessing mobile device proficiency. (2018, December). "JAG: A New Tool for Assessing Mobile Device Proficiency in Older Adults: The Mobile Device Proficiency Questionnaire." http://sagenursing.sage-publications.libsynpro.com/jag-a-new-tool-for-assessing-mobile-device-proficiency-in-older-adults-the-mobile-device-proficiency-questionnaire-0
- Roque, N. A., and Boot, W. R., provided audio commentary on the state of assessing mobile device proficiency. (2018, November). "JAG: A New Tool for Assessing Mobile Device Proficiency in Older Adults: The Mobile Device Proficiency Questionnaire." http://sagenursing.sage-publications.libsynpro.com/jag-a-new-tool-for-assessing-mobile-device-proficiency-in-older-adults-the-mobile-device-proficiency-questionnaire
