#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def read(path):
    return (ROOT / path).read_text(encoding="utf-8")


def numbered_count(text):
    return len(re.findall(r"^1\.\s+", text, flags=re.MULTILINE))


def money_values(text):
    return [int(m.replace(",", "")) for m in re.findall(r"\$([0-9][0-9,]+)", text)]


def grant_blocks(text):
    return re.findall(r"::: \{\.grant\}\n(.*?)\n:::", text, flags=re.DOTALL)


def active_period(period):
    return bool(re.search(r"202[6-9]|203[0-9]", period))


peer_reviewed = read("sections/publications/peer-reviewed.qmd")
book_chapters = read("sections/publications/book-chapters.qmd")
funding = read("sections/funding.qmd")
presentations = read("sections/presentations/presentations.qmd")
service = read("sections/service.qmd")
outreach = read("sections/outreach_science.qmd")

grants = grant_blocks(funding)
grant_amounts = []
active_external = 0
nih_grants = 0
for grant in grants:
    amount_match = re.search(r"\*\*Total Costs:\*\*\s+\$([0-9][0-9,]+)", grant)
    if amount_match:
        grant_amounts.append(int(amount_match.group(1).replace(",", "")))
    if "NIH" in grant or "NIA" in grant:
        nih_grants += 1
    if active_period(grant):
        active_external += 1

invited_section = presentations.split("### Invited Talks", 1)[1].split("### Organized Symposia", 1)[0]
media_block = outreach.split("### Scientific and Professional Outreach", 1)[0]
media_items = [
    line for line in media_block.splitlines()
    if line.startswith("- ") and "http" in line
]
leadership_terms = [
    "Core Leader",
    "Co-Core Leader",
    "Program Chair",
]
program_leadership = sum(
    len(re.findall(rf"(?<!-)\b{re.escape(term)}\b", service))
    + len(re.findall(rf"(?<!-)\b{re.escape(term)}\b", funding))
    for term in leadership_terms
)
nih_reviewer_service = sum(
    1 for line in service.splitlines()
    if "Early Career Reviewer" in line
    and ("National Institutes of Health" in line or "NIH" in line)
)

rows = [
    ("Peer-reviewed publications", str(numbered_count(peer_reviewed))),
    ("Books / chapters", str(numbered_count(book_chapters))),
    ("Current external funding", str(active_external)),
    ("Total external funding", f"${sum(grant_amounts):,}"),
    ("Invited talks", str(numbered_count(invited_section))),
    ("NIH grants", str(nih_grants)),
    ("Program leadership roles", str(program_leadership)),
    ("NIH reviewer service", str(nih_reviewer_service)),
    ("Major media coverage", str(len(media_items))),
]

out = ROOT / "sections" / "career-highlights.qmd"
out.write_text(
    "<!-- Generated by scripts/generate_career_highlights.py. Do not edit by hand. -->\n\n"
    "## Career Highlights\n\n"
    "::: {.highlight-table .compact-table}\n\n"
    "| Metric | Count / Amount | Metric | Count / Amount |\n"
    "|---|---:|---|---:|\n"
    + "\n".join(
        f"| {left[0]} | {left[1]} | {right[0]} | {right[1]} |"
        for left, right in zip(rows[0::2], rows[1::2])
    )
    + (f"\n| {rows[-1][0]} | {rows[-1][1]} |  |  |" if len(rows) % 2 else "")
    + "\n\n:::\n",
    encoding="utf-8",
)
