### External Research Funding

1. NIA-5R01AG080635-03 . Validation of the Remote Cognitive Aging and Alzheimer’s Disease Research (R-CARE) Toolbox for Diverse Populations. Nelson A. Roque (Principal Investigator of subaward; Prime: Albert Einstein College of Medicine). National Institute on Aging (NIA), National Institutes of Health. $868,564 total costs awarded. Active Dates 2023–2028.
2. NIA- 5R21AG078846-02. Perceived Ethnic Discrimination and Cognitive Function in Mexican-origin Adults. Nelson A. Roque (Principal Investigator of subaward; Prime: University of Texas at Austin; Principal Investigator: Dr. Liz Muñoz). National Institute on Aging (NIA), National Institutes of Health. $90,232 total costs awarded. Active Dates 2022–2024.
3. NIA-5P01AG003949-12. Einstein Aging Study (as part of renewal of NIA-5P01AG003949), Project: Air Pollution and Cognitive Function. Nelson A. Roque (Co-Principal Investigator; Albert Einstein College of Medicine; Co-Principal Investigator: Dr. Charles B. Hall). National Institute on Aging (NIA), National Institutes of Health. $911,768 total costs awarded (35% allocation). Active Dates 2022–2027.
4. NIA-5P01AG003949-12 . Einstein Aging Study (as part of renewal of NIA-5P01AG003949), Core: Technology and Data Management Core. Nelson A. Roque (Core Leader; Principal Investigator of subaward). National Institute on Aging (NIA), National Institutes of Health. $1,696,559 total costs awarded (19% allocation). Active Dates 2022–2027.
5. NIA-U2CAG060408. Mobile Monitoring of Cognitive Change (M2C2). Nelson A. Roque (Principal Investigator of subaward while at University of Central Florida). National Institute on Aging (NIA), National Institutes of Health. $50,000 total costs awarded. Active Dates 2022–2023.
6. NIA-R44AG056250. A Non-Pharmacological Multi-Modal Therapy to Improve Sleep and Cognition and Reduce Mild Cognitive Impairment Risk. Nelson A. Roque (Principal Investigator of subaward while at the University of Central Florida). Proactive Life, Inc. $14,685 total costs awarded. Active Dates 2021–2022.
7. NIA-R03AG067009. Investigating Medication Errors in Daily Life: Discovering Person-specific and Situation-specific Risk Factors. Nelson A. Roque (Principal Investigator). National Institute on Aging (NIA), National Institutes of Health. $149,000 total costs awarded. Active Dates July 2020–May 2022 (second no-cost extension requested).
